### ISSUE TITLE
Error if tokenstream contains a $metavariable

### ISSUE THREAD

**Issue by dtolnay** [oxidecomputer/serde_tokenstream#1]
Using the example Config data structures and macro in the readme, the following invocation from inside of macro_rules fails to deserialize.

```rust
macro_rules! repro {
    ($owner:literal) => {
        #[MyMacro {
            name = "SNPP",
            owner = $owner,
            details = {
                type = Fission,
                year_of_opening = 1968,
            }
        }]
        fn some_func() {}
    };
}

repro!("Canary M Burns");
```

```console
error: expected a string, but found ` "Canary M Burns" `
  --> src/main.rs:7:21
   |
7  |             owner = $owner,
   |                     ^^^^^^
...
17 | repro!("Canary M Burns");
   | ------------------------- in this macro invocation
```

These are represented in proc macro input as a [Group](https://doc.rust-lang.org/proc_macro/struct.Group.html) whose [delimiter](https://doc.rust-lang.org/proc_macro/struct.Group.html#method.delimiter) is [None](https://doc.rust-lang.org/proc_macro/enum.Delimiter.html#variant.None). Proc macros that parse using [syn's ParseStream](https://docs.rs/syn/1.0.21/syn/parse/index.html) instead of directly parsing a TokenStream don't need to think about these because ParseStream transparently enters None-delimited groups when appropriate, but code that parses TokenStream has to handle it explicitly.

```console
Ident {
    ident: "owner",
    span: #3 bytes(127..132),
},
Punct {
    ch: '=',
    spacing: Alone,
    span: #3 bytes(133..134),
},
Group {
    delimiter: None,
    stream: TokenStream [
        Literal {
            lit: Lit {
                kind: Str,
                symbol: "Canary M Burns",
                suffix: None,
            },
            span: #3 bytes(135..141),
        },
    ],
    span: #3 bytes(135..141),
},
```

**Comment by ahl** [comment]
Thanks for the issue; nice find! I had explored Groups with None delimiters, but hadn't been quite sure how to conjure them.

I looked into using `ParseStream` but couldn't figure out how to use it for my purposes.

I believe I fixed this issue and related problems by removing an inefficient use of `syn::parse_str()` and replacing it with a cleaner call to `syn::parse2()`.
