### ISSUE TITLE
Cover the full range of item with error

### ISSUE THREAD

**Issue by dtolnay** [oxidecomputer/serde_tokenstream#3]
Filing to track this TODO in deserialize_ignored_any:

https://github.com/oxidecomputer/serde_tokenstream/blob/67c3d3c34150e64f9b1300642593cce1521d913c/src/serde_tokenstream.rs#L758-L760

https://docs.rs/syn/1.0.21/syn/struct.Error.html#method.new_spanned can produce errors spanning multiple tokens without using `join`.

**Comment by ahl** [comment]
Very cool; thanks for the pointer!
