### ISSUE TITLE
Unclear examples for derive macro

### ISSUE THREAD

**Issue by ijsnow** [oxidecomputer/serde_tokenstream#92]
How do you de-serialize info from an attribute for a derive macro? See the example code below.

```rust
#[derive(Debug, Default, Deserialize)]
pub struct Settings {
    my_field: Vec<(String, f32)>,
}

#[test]
fn test_parse_settings() {
    let input: syn::DeriveInput = syn::parse2(quote::quote! {
        #[settings {
            my_field = [("Jumbo", 42.)]
        }]
        struct MyItem;
    })
    .unwrap();

    let settings: Settings =
        serde_tokenstream::from_tokenstream(&input.attrs[0].tokens).expect("deserialize");
        // error expecting an ident

    let tokens = &input.attrs[0].tokens;

    let to_parse = quote::quote! {
        settings #tokens
    };

    let settings: Settings =
        serde_tokenstream::from_tokenstream(dbg!(&to_parse)).expect("deserialize");
        // error expecting `=`

    let tokens = &input.attrs[0].tokens;

    let to_parse = quote::quote! {
        settings = #tokens
    };

    let settings: Settings =
        serde_tokenstream::from_tokenstream(dbg!(&to_parse)).expect("deserialize");
        // error extraneous values `settings` and `my_field`     
}
```

I also tried changing the capitalization of `settings` in the `quote!`.

I've looked through the test cases and docs and can't figure out how to do what I'm wanting to do. 

EDIT: It would also be great to be able to deserialize from the macro meta syntax used in `syn` for attributes (`#[settings(my = "fields")]`).

**Comment by ahl** [comment]
An attribute macro (surprisingly) receives a `TokenStream` of the contents of the `Group` rather than all tokens after the identifier:
```rust
// Example: Multiple tokens in the input
#[show_streams(multiple => tokens)]
fn invoke3() {}
// out: attr: "multiple => tokens"
// out: item: "fn invoke3() {}"
```
https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros

This is where `serde_tokenstream` is most typically used.

In the case you've specified, you'll see **all** tokens in the attribute; to satisfy the expectations of `from_tokenstream()` extract the initial group:

```rust
    let input: syn::DeriveInput = syn::parse2(quote::quote! {
        #[handle {
            my_field = [("Jumbo", 42.)]
        }]
        struct MyItem;
    })
    .unwrap();

    let tokens = match input.attrs[0].tokens.clone().into_iter().next() {
        Some(TokenTree::Group(grp)) => grp.stream(),
        _ => panic!(),
    };

    let settings: Settings = serde_tokenstream::from_tokenstream(&tokens).expect("deserialize");
    println!("{:#?}", settings);
```

```
Settings {
    my_field: [
        (
            "Jumbo",
            42.0,
        ),
    ],
}
```

Certainly this is non-obvious! I could imagine either documentation here, or--perhaps--serde_tokenstream could simply accept a Group token and handle it heuristically in infer this case.

**Comment by ahl** [comment]
Neat! You're building a derive macro with some annotations in the item to control how you derive things?
